In [2]:
import numpy as np

# Numpy Basics

## NumPy Data Types (dtypes)

NumPy offers a variety of data types for handling numerical and other types of data efficiently.

Reference: <a href="https://numpy.org/doc/stable/user/basics.types.html">Data types @numpy.org</a>

We can check the data type of array elements by `arr.dtype` attribute 

In [3]:
arr = np.array([1,2,3], dtype=np.int8)
arr.dtype

dtype('int8')

### Basic Data types

### Integer Types

**Signed Integer Types**: Represent whole numbers, can be positive or negative.

**Unsigned Integer Types**: Represent non-negative whole numbers.

In [4]:
# Signed 8-bit integer
int8_array = np.array([1, -2, 3], dtype=np.int8)
print(int8_array)

# Signed 16-bit integer
int16_array = np.array([1000, -2000, 3000], dtype=np.int16)
print(int16_array)

# Unsigned 8-bit integer
uint8_array = np.array([1, 2, 3], dtype=np.uint8)
print(uint8_array)

# Unsigned 16-bit integer
uint16_array = np.array([1000, 2000, 3000], dtype=np.uint16)
print(uint16_array)

[ 1 -2  3]
[ 1000 -2000  3000]
[1 2 3]
[1000 2000 3000]


### Floating-Point Types

Floating-Point Types represent real numbers with decimal points.

In [5]:
# 32-bit floating point
float32_array = np.array([1.5, 2.5, 3.5], dtype=np.float32)
print(float32_array)

# 64-bit floating point
float64_array = np.array([1.1, 2.2, 3.3], dtype=np.float64)
print(float64_array)

[1.5 2.5 3.5]
[1.1 2.2 3.3]


### Complex Types

Represent complex numbers with real and imaginary parts.

In [6]:
# 64-bit complex number
complex64_array = np.array([1+2j, 3+4j], dtype=np.complex64)
print(complex64_array)

# 128-bit complex number
complex128_array = np.array([5+6j, 7+8j], dtype=np.complex128)
print(complex128_array)

[1.+2.j 3.+4.j]
[5.+6.j 7.+8.j]


### Boolean Type

Represents boolean values (True or False).

In [7]:
# Boolean array
bool_array = np.array([1, 0, 1,0], dtype=np.bool_)
print(bool_array)

[ True False  True False]


### String Types

Represents fixed-length Unicode string type.

In [8]:
# Unicode string array
str_array = np.array(['a', 'bc', 'def'], dtype=np.str_)
print(str_array)
print(str_array.dtype)

['a' 'bc' 'def']
<U3


### Object Type

Represent arbitrary Python objects

In [9]:
# Object array
obj_array = np.array([1, 'a', [2, 3]], dtype=np.object_)
print(obj_array)
print(obj_array.dtype)

[1 'a' list([2, 3])]
object


### Datetime

For dates and times.

In [10]:
# Datetime array
datetime_array = np.array(['2020-01-01', '2021-01-01'], dtype=np.datetime64)
print(datetime_array)  # Output: ['2020-01-01' '2021-01-01']
print(datetime_array.dtype)  # Output: datetime64

['2020-01-01' '2021-01-01']
datetime64[D]


### Convert from one datatype to another 

#### Using data types functions

Data-types can be used as functions to convert from one data type to another

In [11]:
# create array of integers
arr = np.array([1,2,3], dtype=np.int8)

# conver it to boolean
print(np.bool_(arr))

# conever it to float
print(np.float64(arr))

[ True  True  True]
[1. 2. 3.]


### Using array.astype() method

To convert the type of an array, use the `array.astype()` method, which is preffered than using dtypes as functions 

In [12]:
# create array of integers
arr = np.array([1,2,3], dtype=np.int8)

# convert it to boolean
print(arr.astype(np.bool_))

# conevert it to float
print(arr.astype(np.float64))

[ True  True  True]
[1. 2. 3.]


## Numpy Array Attributes

In [18]:
a = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    dtype=np.int8
)

print(a.shape)
print(a.size*a.itemsize)

(2, 3)
6


In [20]:
l = range(5)
list(l)

[0, 1, 2, 3, 4]

In [22]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [24]:
a_ln = np.linspace(1, 10, 5)
a_ln

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
a_lg = np.logspace(1, 10, 5)
a_lg

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

## Numpy Operations

In [30]:
arr1 = np.arange(5)
arr2 = np.full(5,2)

print(f'arr1: {arr1}')
print(f'arr2: {arr2}')

arr1: [0 1 2 3 4]
arr2: [2 2 2 2 2]


In [32]:
arr1 / arr2

array([0. , 0.5, 1. , 1.5, 2. ])

In [33]:
arr1>arr2

array([False, False, False,  True,  True])

In [34]:
print(f'arr1: {arr1}')
print(f'arr2: {arr2}')

arr1: [0 1 2 3 4]
arr2: [2 2 2 2 2]


In [38]:
abool1 = arr1>arr2
abool2 = arr1==arr2

print(abool1)
print(abool2)

[False False False  True  True]
[False False  True False False]


In [39]:
abool2 & abool1

array([False, False, False, False, False])

In [41]:
np.any(abool1)

True

## Indexing

In [45]:
a = np.arange(1,11).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
print( a[0,3])

4
