In [1]:
import numpy as np

# NumPy Data Types (dtypes)

NumPy offers a variety of data types for handling numerical and other types of data efficiently.

Reference: <a href="https://numpy.org/doc/stable/user/basics.types.html">Data types @numpy.org</a>

We can check the data type of array elements by `arr.dtype` attribute 

In [3]:
arr = np.array([1,2,3], dtype=np.int8)
arr.dtype

dtype('int8')

## Basic Data types

### Integer Types

**Signed Integer Types**: Represent whole numbers, can be positive or negative.

**Unsigned Integer Types**: Represent non-negative whole numbers.

In [6]:
# Signed 8-bit integer
int8_array = np.array([1, -2, 3], dtype=np.int8)
print(int8_array)

# Signed 16-bit integer
int16_array = np.array([1000, -2000, 3000], dtype=np.int16)
print(int16_array)

# Unsigned 8-bit integer
uint8_array = np.array([1, 2, 3], dtype=np.uint8)
print(uint8_array)

# Unsigned 16-bit integer
uint16_array = np.array([1000, 2000, 3000], dtype=np.uint16)
print(uint16_array)

[ 1 -2  3]
[ 1000 -2000  3000]
[1 2 3]
[1000 2000 3000]


### Floating-Point Types

Floating-Point Types represent real numbers with decimal points.

In [7]:
# 32-bit floating point
float32_array = np.array([1.5, 2.5, 3.5], dtype=np.float32)
print(float32_array)

# 64-bit floating point
float64_array = np.array([1.1, 2.2, 3.3], dtype=np.float64)
print(float64_array)

[1.5 2.5 3.5]
[1.1 2.2 3.3]


### Complex Types

Represent complex numbers with real and imaginary parts.

In [9]:
# 64-bit complex number
complex64_array = np.array([1+2j, 3+4j], dtype=np.complex64)
print(complex64_array)

# 128-bit complex number
complex128_array = np.array([5+6j, 7+8j], dtype=np.complex128)
print(complex128_array)

[1.+2.j 3.+4.j]
[5.+6.j 7.+8.j]


### Boolean Type

Represents boolean values (True or False).

In [6]:
# Boolean array
bool_array = np.array([1, 0, 1,0], dtype=np.bool_)
print(bool_array)

[ True False  True False]


### String Types

Represents fixed-length Unicode string type.

In [13]:
# Unicode string array
str_array = np.array(['a', 'bc', 'def'], dtype=np.str_)
print(str_array)
print(str_array.dtype)

['a' 'bc' 'def']
<U3


### Object Type

Represent arbitrary Python objects

In [9]:
# Object array
obj_array = np.array([1, 'a', [2, 3]], dtype=np.object_)
print(obj_array)
print(obj_array.dtype)

[1 'a' list([2, 3])]
object


### Datetime

For dates and times.

In [17]:
# Datetime array
datetime_array = np.array(['2020-01-01', '2021-01-01'], dtype=np.datetime64)
print(datetime_array)  # Output: ['2020-01-01' '2021-01-01']
print(datetime_array.dtype)  # Output: datetime64

['2020-01-01' '2021-01-01']
datetime64[D]


## Convert from one datatype to another 

### Using data types functions

Data-types can be used as functions to convert from one data type to another

In [10]:
# create array of integers
arr = np.array([1,2,3], dtype=np.int8)

# conver it to boolean
print(np.bool_(arr))

# conever it to float
print(np.float64(arr))

[ True  True  True]
[1. 2. 3.]


### Using array.astype() method

To convert the type of an array, use the `array.astype()` method, which is preffered than using dtypes as functions 

In [11]:
# create array of integers
arr = np.array([1,2,3], dtype=np.int8)

# convert it to boolean
print(arr.astype(np.bool_))

# conevert it to float
print(arr.astype(np.float64))

[ True  True  True]
[1. 2. 3.]
